FROM node:18-alpine

ARG BACKEND_API_URL
# vite requires env vars get prefixed with VITE_
ENV VITE_BACKEND_API_URL=$BACKEND_API_URL

WORKDIR /app

COPY . .

RUN rm -f /usr/local/bin/yarn /usr/local/bin/yarnpkg

RUN corepack enable && corepack prepare --activate && yarn install

CMD ["yarn", "dev"]
